SCHEMA = [
    ('PRODID',  ('PRODID', 1)),
    ('UID',     ('UID', 1)),
    ('FN',      ('Full name', 1)),
    ('N',       ('Name', 1)),
    ('ADR',     ('Address', 3)),
    ('TEL',     ('Phone', 6)),
    ('EMAIL',   ('E-Mail', 3)),
    ('NOTE',    ('Note', 1)),
    ('CATEGORIES',    ('Categories', 1)),
    ('GENDER',  ('Gender', 1)),
    ('TITLE',   ('Title', 1)),
    ('BDAY',    ('Birthday', 1)),
    ('ORG',     ('Organization', 1)),
    ('IMPP',    ('IM', 3)),
    ('PHOTO',   ('Photo', 1)),
    ('REV',     ('Revision', 1)),
]